import = ["/home/nabby27/.config/alacritty/themes/themes/one_dark.toml"]

[env]
TERM = "alacritty"

[font]
size = 12.5

[font.bold]
family = "JetBrainsMono Nerd Font"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.normal]
family = "JetBrainsMono Nerd Font"

[font.offset]
x = 1
y = 2

[window]
decorations = "none"
dynamic_title = true
opacity = 1.00
startup_mode = "Maximized"

[window.padding]
x = 0
y = 9
